name: zinggo_social

description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_core: ^1.18.0
  bloc_concurrency:
  flutter_reaction_button: ^2.0.1+2
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.20
  flutter_signin_button: ^2.0.0
  email_validator: ^2.0.1
  cloud_firestore: ^3.2.1
  dio: ^4.0.1
  overlay_support: ^2.0.0
  path_provider: ^2.0.10
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.1.0
  image_gallery_saver: ^1.7.1
  gallery_saver: ^2.3.2
  shared_preferences: ^2.0.8
  permission_handler: ^8.2.6
  multi_image_picker2: ^5.0.2
  carousel_slider: ^4.1.1
  flutter_facebook_auth: ^4.4.1+1
  flutter_login_facebook: ^1.6.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  screenshot: ^1.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1




flutter:


  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/2x/
    - assets/images/3x/
    - assets/images/background_img/
    - assets/images/icons/
    - assets/images/
    - assets/images/icons/navigationbar/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
